FROM python:3.6-slim

# Apt-install mysql client and cleanup temporary files afterwards
RUN apt-get update && \
    apt-get install --force-yes -y --no-install-recommends \
        mysql-client \
        git vim liblua5.1-dev libmagickwand-dev \
        build-essential && \
    apt-get clean
RUN rm -rf  /tmp/* /var/tmp/*

COPY requirements.txt /tmp/requirements.txt

RUN python3 -m pip install -r /tmp/requirements.txt

ADD . /code/
WORKDIR /code/

RUN python3 -m pip install -e .

# Main entrypoint and the default command that will be run
CMD ["/usr/local/bin/python3.6", "server.py"]

# Game server runs on 8000/tcp, lobby server runs on 8001/tcp, nat echo server runs on 30351/udp
EXPOSE 8000 8001 30351

RUN python3 -V
