#!/bin/bash
set -e

apt-get -y update
apt-get -y install nfs-common portmap # for nfs support

echo "========================================================"
uname -a
echo "Important: Manually update kernel to 3.8:"
echo "$ sudo apt-get install linux-image-generic-lts-raring linux-headers-generic-lts-raring"
echo "$ sudo reboot"
echo "========================================================"