# Run static analysis
name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install isort

      - run: isort . --check --diff

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 6.0.0
          plugins: flake8-quotes~=3.3
